title: "@junee"
description: mga himaya sa huna-huna.
github_username: junleepepito

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
    values:
      layout: "default"

# ✅ Allow Jekyll to process files in the _pages folder
include:
  - _pages

permalink: /:categories/:year/:month/:day/:title/
